### ISSUE TITLE
sb-server-runner crashing

### ISSUE THREAD

**Issue by calvinbui** [mchangrh/sb-mirror#8]
I am using the `mchangrh/sb-server-runner:latest` image directly with postgres.

```
Licenced under the MIT Licence https://github.com/ajayyy/SponsorBlockServer
mv: can't rename '/build/node_modules': No such file or directory

> sponsor_block_server@0.1.0 start
> ts-node src/index.ts

 WARN  2021-10-29T13:06:36.211Z:   [dumpDatabase] No tables configured
/bin/sh: git: not found
'Error: Command failed: git rev-parse HEAD\n' +
  '/bin/sh: git: not found\n' +
  '\n' +
  '    at checkExecSyncError (node:child_process:826:11)\n' +
  '    at execSync (node:child_process:900:15)\n' +
  '    at getCommit (/app/src/utils/getCommit.ts:4:47)\n' +
  '    at /app/src/index.ts:21:24\n' +
  '    at Generator.next (<anonymous>)\n' +
  '    at fulfilled (/app/src/index.ts:5:58)\n' +
  '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
```

**Comment by mchangrh** [comment]
Oh I thought it was git for the entrypoint

**Comment by mchangrh** [comment]
I won't be able to test for a few hours but I'll push a fix on mobile

**Comment by mchangrh** [comment]
resolved in https://github.com/mchangrh/sb-mirror/commit/098963e6b5ec4acaae361f4c131c5c57bfe6fe47#diff-4c59301bef230a46870c6ab00443e1a4c1c3f06a2bfd0bdc7e12155e99e4dd20
